version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      compose:
        patterns:
          - "androidx.compose*"
      androidx:
        patterns:
          - "androidx.*"
        exclude-patterns:
          - "androidx.compose*"
      hilt:
        patterns:
          - "com.google.dagger*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
